name: Print PR Title

on:
  pull_request:
    types: [opened]

jobs:
  print-title:
    runs-on: ubuntu-latest
    steps:
      - name: Print pull request title
        run: |
          echo '${{ github.event.pull_request.title }}'
